### ISSUE TITLE
インストール方法

### ISSUE THREAD

**Issue by espresso3389** [ytabuchi/XamarinFormsTemplate#3]
前から思ってたんですが、インストール方法、git clone で直接ぶち込んだり、あるいは、 zip を直接展開する方法でイケると思います。

こういうのって、 README.md に直接 pull-req でも良いのかな？って思うんですが、ぶっちゃけ、勝手に文章書き換えは良いのか悪いのか分からないので、Issue としてぶっ込みました。

以下、草案：

# Option 1: Clone the Repository (Recommended)
Clone the project on the following location directly:
```%USERPROFILE%\Documents\Visual Studio 2015\Templates\ProjectTemplates\Visual C#```
That is, on a command prompt, you can install the template by the following commands:
```
cd "%USERPROFILE%\Documents\Visual Studio 2015\Templates\ProjectTemplates\Visual C#"
git clone https://github.com/ytabuchi/XamarinFormsTemplate.git
```
After the first installation, you can of course update your copy by ```git pull``` and you feel it's easier to update the templates than the other option.

# Option 2: Download the ZIP
- Download XamarinFormsTemplate-master.zip file from [GitHub](https://github.com/ytabuchi/XamarinFormsTemplate/archive/master.zip)
- Extract the zip file
- Move the extracted ```XamarinFormsTemplate-master``` folder to the following location:
```%USERPROFILE%\Documents\Visual Studio 2015\Templates\ProjectTemplates\Visual C#```

**Comment by espresso3389** [comment]
こういうのって、 README.md に直接 pull-req でも良いのかな？って思うんですが、ぶっちゃけ、勝手に文章書き換えは良いのか悪いのか分からないので、Issue としてぶっ込みました。

**Comment by ytabuchi** [comment]
コメントありがとうございます。zipじゃなくても認識されるの初めて知りました…！これにしましょう。

**Comment by espresso3389** [comment]
本当は、ZIPに無駄な階層がなければZIPダウンロードは良い方法なんですけどねぇ。間に余計な階層が入ってると認識してくれないみたいで残念ですね。

**Comment by ytabuchi** [comment]
うんうん。それでわざわざDLして再zipしてもらってましたが、素で行けるならそれで全然良いかと！ありがとうございました。
