### ISSUE TITLE
Visual studio error blocking user interaction

### ISSUE THREAD

**Issue by sirfilipef** [ytabuchi/XamarinFormsTemplate#4]
When i create a new Xamarin forms project from the template this error occurs.

Any idea?

![capture](https://cloud.githubusercontent.com/assets/7373946/22403798/55a2b12c-e61a-11e6-80e7-d823b5a86b2d.PNG)

**Comment by ytabuchi** [comment]
Hi, 
VS has the showed issue sometimes. I don't know when it could be showed so unfortunately I don't have any idea.
I think it become from another topic? It will be gone with restarting Visual Studio.
