### ISSUE TITLE
Resource.Designer.cs is missing in Android project template

### ISSUE THREAD

**Issue by tafuji** [ytabuchi/XamarinFormsTemplate#7]
### Steps to Reproduce
Create a new project with XamarinFormsTemplate.

### Expected Behavior
Android project is created successfully.

### Actual Behavior
Android project is NOT created because of an error. (see the following attached file)

![resource designer cs - missing](https://user-images.githubusercontent.com/14265774/42489109-24673a5a-8444-11e8-9cb1-6b0cf8fd4a89.png)

### Cause

- Missing Resource.Designer.cs file in the Android project template items.
- Resource.Designer.cs file should be placed under the ```XFApp.Android/Resources``` folder.

**Comment by ytabuchi** [comment]
I worry that you have added a standard .gitignore including Resource.Designer.cs to your FORKED repository ?

My repository does not have gitignore.
